#pragma once
#define CONFIG_WS_V1_DISPLAY 1
#define CONFIG_WS_V1_TOUCH_CONFIRM 1
#define CONFIG_WS_V1_BRIGHTNESS 90
#define CONFIG_WS_V1_DIM_AFTER_SECONDS 30
#define FIDO_V1_BOOT_CONFIRM_FALLBACK 0
#define FIDO_V1_UV_TIMEOUT_SECONDS 120
