#pragma once

enum {
    DUCKY_MOD_LEFT_CTRL = 1U << 0,
    DUCKY_MOD_LEFT_SHIFT = 1U << 1,
    DUCKY_MOD_LEFT_ALT = 1U << 2,
    DUCKY_MOD_LEFT_GUI = 1U << 3,
    DUCKY_MOD_RIGHT_CTRL = 1U << 4,
    DUCKY_MOD_RIGHT_SHIFT = 1U << 5,
    DUCKY_MOD_RIGHT_ALT = 1U << 6,
    DUCKY_MOD_RIGHT_GUI = 1U << 7,
};

enum {
    DUCKY_MOUSE_LEFT = 1U << 0,
    DUCKY_MOUSE_RIGHT = 1U << 1,
    DUCKY_MOUSE_MIDDLE = 1U << 2,
    DUCKY_MOUSE_BACK = 1U << 3,
    DUCKY_MOUSE_FORWARD = 1U << 4,
};

enum {
    DUCKY_LED_NUM_LOCK = 1U << 0,
    DUCKY_LED_CAPS_LOCK = 1U << 1,
    DUCKY_LED_SCROLL_LOCK = 1U << 2,
};

enum {
    DUCKY_CONSUMER_PLAY_PAUSE = 0x00CD,
    DUCKY_CONSUMER_SCAN_NEXT = 0x00B5,
    DUCKY_CONSUMER_SCAN_PREVIOUS = 0x00B6,
    DUCKY_CONSUMER_STOP = 0x00B7,
    DUCKY_CONSUMER_EJECT = 0x00B8,
    DUCKY_CONSUMER_MUTE = 0x00E2,
    DUCKY_CONSUMER_VOLUME_UP = 0x00E9,
    DUCKY_CONSUMER_VOLUME_DOWN = 0x00EA,
    DUCKY_CONSUMER_BRIGHTNESS_UP = 0x006F,
    DUCKY_CONSUMER_BRIGHTNESS_DOWN = 0x0070,
};

enum {
    DUCKY_SYSTEM_POWER_DOWN = 1,
    DUCKY_SYSTEM_SLEEP = 2,
    DUCKY_SYSTEM_WAKE = 3,
};
