#!/usr/bin/env python3
# SPDX-License-Identifier: AGPL-3.0-or-later
"""Generate the antialiased 120 px Settings gear as an LVGL A8 mask."""
from math import cos, pi, sin
from pathlib import Path

from PIL import Image, ImageDraw


ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "templates" / "port" / "ws_settings_icon_asset.h"
PREVIEW = ROOT.parent / "docs" / "gui" / "EVILKEY_SETTINGS_ICON_PREVIEW.png"
SIZE = 120
SCALE = 8


def rounded_outline(points, radius=2.8):
    """Round each polygon corner with a sampled quadratic curve."""
    outline = []
    for i, point in enumerate(points):
        previous, following = points[i-1], points[(i+1) % len(points)]
        before = (previous[0]-point[0], previous[1]-point[1])
        after = (following[0]-point[0], following[1]-point[1])
        before_length = (before[0]**2+before[1]**2)**0.5
        after_length = (after[0]**2+after[1]**2)**0.5
        distance = min(radius, before_length/3, after_length/3)
        start = tuple(point[k]+before[k]*distance/before_length for k in range(2))
        end = tuple(point[k]+after[k]*distance/after_length for k in range(2))
        for step in range(13):
            t = step/12
            outline.append(tuple(((1-t)**2*start[k]+2*(1-t)*t*point[k]+t*t*end[k])*SCALE
                                 for k in range(2)))
    return outline


def gear_outline():
    """Shared original contour for the A8 mask and Jet geometry."""
    outline = []
    for tooth in range(8):
        angle = tooth * 2 * pi / 8 - pi / 2
        for degrees, radius in ((-18, 36), (-12, 36), (-8, 46),
                                (8, 46), (12, 36), (18, 36)):
            a = angle + degrees * pi / 180
            outline.append((SIZE/2 + radius * cos(a), SIZE/2 + radius * sin(a)))
    return rounded_outline(outline)


def render() -> Image.Image:
    """Eight rounded teeth, a dark body and clean theme-tintable outlines."""
    size = SIZE * SCALE
    center = size / 2
    mask = Image.new("L", (size, size), 0)
    draw = ImageDraw.Draw(mask)
    outline = gear_outline()
    # Low-alpha fill on black gives the same dark teal surface as Apps tiles.
    # The bright border is about two device pixels, with smooth rounded flanks.
    draw.polygon(outline, fill=38)
    draw.line(outline+[outline[0]], fill=240, width=2*SCALE, joint="curve")
    recess = 24*SCALE
    draw.ellipse((center-recess,center-recess,center+recess,center+recess),
                 fill=22, outline=84, width=SCALE)
    hole = 14 * SCALE
    draw.ellipse((center - hole, center - hole,
                  center + hole, center + hole), fill=0, outline=240, width=2*SCALE)
    antialiased = mask.resize((SIZE, SIZE), Image.Resampling.LANCZOS)
    return antialiased.point([0 if a < 5 else 255 if a > 250 else a
                              for a in range(256)])


def main() -> None:
    mask = render()
    data = mask.tobytes()
    lines = [
        "/* SPDX-License-Identifier: AGPL-3.0-or-later",
        " * Generated by firmware/tools/build_settings_icon_asset.py.",
        " * Rounded eight-tooth gear with dark fill and theme-tintable outlines. */",
        "#pragma once", "",
        f"static const uint8_t ws_settings_gear_map[{len(data)}] = {{",
    ]
    for start in range(0, len(data), 20):
        lines.append("    " + ",".join(map(str, data[start:start + 20])) + ",")
    lines += [
        "};", "",
        "static const lv_img_dsc_t ws_settings_gear = {",
        "    .header.cf = LV_IMG_CF_ALPHA_8BIT,",
        "    .header.always_zero = 0,",
        "    .header.reserved = 0,",
        f"    .header.w = {SIZE},",
        f"    .header.h = {SIZE},",
        "    .data_size = sizeof(ws_settings_gear_map),",
        "    .data = ws_settings_gear_map,",
        "};", "",
    ]
    OUT.write_text("\n".join(lines), encoding="utf-8")
    preview = Image.new("RGB", (180, 180), "#000000")
    accent = Image.new("RGB", (SIZE, SIZE), "#4DE3C1")
    preview.paste(accent, (30, 30), mask)
    PREVIEW.parent.mkdir(parents=True, exist_ok=True)
    preview.save(PREVIEW)
    print(f"Generated {OUT} ({len(data)} A8 bytes)")
    print(f"Preview: {PREVIEW}")


if __name__ == "__main__":
    main()
