#!/usr/bin/env python3
"""Generate 72 RGB565-friendly indexed frames for the approved crystal.

One 180-degree half-turn is stored: the octahedron is 180-degree symmetric.
The firmware repeats it twice for one 360-degree vertical-axis rotation.
"""
from __future__ import annotations

import math
from pathlib import Path

from crystal_geometry import crystal_layer

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "templates/port/ws_crystal_assets.h"
WIDTH, HEIGHT = 46, 76
CROP = (21, 6, 67, 82)
FRAMES = 72
PALETTE = [(0, 0, 0, 0)]
PALETTE += [(255, 255, 255, a) for a in (48, 96, 152, 208)]
PALETTE += [(v, min(255, v + 5), min(255, v + 10), 255)
            for v in (124, 138, 152, 166, 180, 194, 208, 222, 236, 248, 255)]


def nearest_index(rgba):
    r, g, b, a = rgba
    if a < 24:
        return 0
    if a < 240:
        return min(range(1, 5), key=lambda i: abs(PALETTE[i][3] - a))
    return min(range(5, 16), key=lambda i: (PALETTE[i][0] - r) ** 2 +
               (PALETTE[i][1] - g) ** 2 + (PALETTE[i][2] - b) ** 2)


def frame_bytes(index):
    image = crystal_layer(2 * math.pi * index / 144).crop(CROP)
    assert image.size == (WIDTH, HEIGHT)
    result = bytearray()
    for r, g, b, a in PALETTE:
        result.extend((b, g, r, a))  # LVGL lv_color32_t is BGRA in memory.
    pixels = image.load()
    for y in range(HEIGHT):
        for x in range(0, WIDTH, 2):
            hi = nearest_index(pixels[x, y])
            lo = nearest_index(pixels[x + 1, y])
            result.append((hi << 4) | lo)
    assert len(result) == 64 + WIDTH * HEIGHT // 2
    return bytes(result)


def main():
    lines = [
        "/* SPDX-License-Identifier: AGPL-3.0-or-later",
        " * Generated by firmware/tools/build_crystal_assets.py.",
        " * 72 frames x 46x76 px, indexed 4-bit with BGRA palette in flash. */",
        "#pragma once", "",
    ]
    for i in range(FRAMES):
        data = frame_bytes(i)
        # LVGL reads the leading BGRA palette through lv_color32_t pointers.
        # Explicit alignment keeps those 32-bit reads safe on ESP32-S3.
        lines.append(f"static const uint8_t ws_crystal_map_{i:02d}[{len(data)}] "
                     "__attribute__((aligned(4))) = {")
        for p in range(0, len(data), 24):
            lines.append("    " + ",".join(str(v) for v in data[p:p + 24]) + ",")
        lines.append("};")
    lines += ["", "static const lv_img_dsc_t ws_crystal_frames[72] = {"]
    for i in range(FRAMES):
        lines.append("    { .header = { .cf = LV_IMG_CF_INDEXED_4BIT, .always_zero = 0, "
                     f".reserved = 0, .w = {WIDTH}, .h = {HEIGHT} }}, "
                     f".data_size = sizeof(ws_crystal_map_{i:02d}), "
                     f".data = ws_crystal_map_{i:02d} }},")
    lines += ["};", ""]
    OUTPUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {FRAMES} crystal frames ({FRAMES * len(frame_bytes(0)):,} image bytes): {OUTPUT}")


if __name__ == "__main__":
    main()
