#!/usr/bin/env python3
"""Build flash-compressed, RGB565-friendly frames of the approved unified mark.

Each 24 ms frame contains a projected mint solid and a projected, vertically
spinning crystal. They are separate LVGL images so the current glitch overlays
and configurable accent continue to affect only the mint layer.
"""
from __future__ import annotations

import sys
import zlib
from pathlib import Path

from PIL import Image, ImageChops, ImageStat

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT.parent / "scripts"))
import render_unified_3d_logo_preview as preview  # noqa: E402

OUTPUT = ROOT / "templates" / "port" / "ws_unified_logo_assets.h"
MINT_BOUNDS = (50, 19, 200, 190)
CRYSTAL_BOUNDS = (97, 139, 151, 216)
MINT_COLORS = 32
CRYSTAL_COLORS = 16


def rgba_layers(phase, mint, sprites):
    coeffs = preview.plane_transform(preview.pose(phase))
    mint_tile, _, _ = preview.slab(mint, phase, coeffs)
    crystal_plane = Image.new("RGBA", (200, 200))
    crystal_plane.alpha_composite(sprites[((phase & 127) * 72) // 128], (81, 119))
    crystal_tile = preview.warp_plane(crystal_plane, coeffs)
    for tile, bounds in ((mint_tile, MINT_BOUNDS),
                         (crystal_tile, CRYSTAL_BOUNDS)):
        box = tile.getbbox()
        assert box and bounds[0] <= box[0] and bounds[1] <= box[1]
        assert box[2] <= bounds[2] and box[3] <= bounds[3]
    return mint_tile.crop(MINT_BOUNDS), crystal_tile.crop(CRYSTAL_BOUNDS)


def asset_frame(image, colors, tint):
    indexed = image.quantize(colors=colors,
                             method=Image.Quantize.FASTOCTREE,
                             dither=Image.Dither.NONE)
    assert indexed.palette.mode == "RGBA"
    indices = indexed.tobytes()
    palette = indexed.palette.getdata()[1][:colors * 4]
    assert len(indices) == image.width * image.height
    assert len(palette) == colors * 4
    # Only the mint material follows the user's accent setting. Grey/white
    # crystal facets retain their original high-contrast neutral palette.
    tint_mask = 0
    for index in set(indices):
        r, g, b, a = palette[index * 4:index * 4 + 4]
        if tint and a and g >= r + 8 and g >= b + 5:
            tint_mask |= 1 << index
    compressed = zlib.compress(indices, 9)
    assert zlib.decompress(compressed) == indices
    reconstructed = indexed.convert("RGBA")
    diff = ImageStat.Stat(ImageChops.difference(image, reconstructed)).mean
    return compressed, palette, tint_mask, max(diff)


def byte_lines(data, columns=24):
    for start in range(0, len(data), columns):
        yield "    " + ",".join(str(v) for v in data[start:start + columns]) + ","


def main():
    mint = preview.saver.logo_masks()[0]
    sprites = [preview.crystal_preview.sprite(i) for i in range(72)]
    streams = [bytearray(), bytearray()]
    metadata = [[], []]
    worst_channel_error = [0.0, 0.0]
    for phase in range(256):
        layers = rgba_layers(phase, mint, sprites)
        for kind, image in enumerate(layers):
            colors = MINT_COLORS if kind == 0 else CRYSTAL_COLORS
            compressed, palette, tint_mask, error = asset_frame(
                image, colors, kind == 0)
            assert len(compressed) < 65536
            metadata[kind].append((len(streams[kind]), len(compressed),
                                   palette, tint_mask))
            streams[kind].extend(compressed)
            worst_channel_error[kind] = max(worst_channel_error[kind], error)
    lines = [
        "/* SPDX-License-Identifier: AGPL-3.0-or-later",
        " * Generated by firmware/tools/build_unified_logo_assets.py.",
        " * 256 x 24 ms frames, zlib-compressed indexed-8 RGBA palettes.",
        " * Crystal and mint share one projective transform; accent tint is mint-only. */",
        "#pragma once", "",
        "#define WS_UNIFIED_PALETTE_BYTES 1024U",
        f"#define WS_UNIFIED_MINT_W {MINT_BOUNDS[2] - MINT_BOUNDS[0]}U",
        f"#define WS_UNIFIED_MINT_H {MINT_BOUNDS[3] - MINT_BOUNDS[1]}U",
        f"#define WS_UNIFIED_MINT_X_OFFSET {MINT_BOUNDS[0] - preview.MARGIN}",
        f"#define WS_UNIFIED_MINT_Y_OFFSET {MINT_BOUNDS[1] - preview.MARGIN}",
        f"#define WS_UNIFIED_CRYSTAL_W {CRYSTAL_BOUNDS[2] - CRYSTAL_BOUNDS[0]}U",
        f"#define WS_UNIFIED_CRYSTAL_H {CRYSTAL_BOUNDS[3] - CRYSTAL_BOUNDS[1]}U",
        f"#define WS_UNIFIED_CRYSTAL_X_OFFSET {CRYSTAL_BOUNDS[0] - preview.MARGIN}",
        f"#define WS_UNIFIED_CRYSTAL_Y_OFFSET {CRYSTAL_BOUNDS[1] - preview.MARGIN}",
        "", 
        "typedef struct {",
        "    uint32_t offset;",
        "    uint16_t length;",
        "    uint32_t mint_tint_mask;",
        "    uint8_t palette_rgba[128];",
        "} ws_unified_mint_frame_t;", "",
        "typedef struct {",
        "    uint32_t offset;",
        "    uint16_t length;",
        "    uint8_t palette_rgba[64];",
        "} ws_unified_crystal_frame_t;", "",
    ]
    for kind, name in enumerate(("mint", "crystal")):
        stream = streams[kind]
        lines.extend([
            f"static const uint8_t ws_unified_{name}_data[{len(stream)}] "
            "__attribute__((aligned(4))) = {",
            *byte_lines(stream),
            "};", "",
            f"static const ws_unified_{name}_frame_t ws_unified_{name}_frames[256] = {{",
        ])
        for offset, length, palette, tint_mask in metadata[kind]:
            if kind == 0:
                fields = f"{offset}U,{length}U,0x{tint_mask:08X}U"
            else:
                fields = f"{offset}U,{length}U"
            lines.append("    {" + fields + ",{" +
                         ",".join(str(v) for v in palette) + "}},")
        lines.extend(["};", ""])
    OUTPUT.write_text("\n".join(lines), encoding="ascii")
    print(f"Wrote {OUTPUT}: mint {len(streams[0]):,} B + crystal "
          f"{len(streams[1]):,} B compressed, "
          f"{256 * (MINT_COLORS + CRYSTAL_COLORS) * 4:,} B palette; "
          f"worst frame mean per-channel error {worst_channel_error}/255")


if __name__ == "__main__":
    main()
