#!/usr/bin/env python3
"""Generate the antialiased 120 px Settings gear as an LVGL A8 mask."""
from math import cos, pi, sin
from pathlib import Path

from PIL import Image, ImageDraw


ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "templates" / "port" / "ws_settings_icon_asset.h"
PREVIEW = ROOT.parent / "docs" / "gui" / "EVILKEY_SETTINGS_ICON_PREVIEW.png"
SIZE = 120
SCALE = 4


def render() -> Image.Image:
    """A true twelve-tooth gear, drawn large and downsampled only once."""
    size = SIZE * SCALE
    center = size / 2
    mask = Image.new("L", (size, size), 0)
    draw = ImageDraw.Draw(mask)
    outline = []
    for tooth in range(12):
        angle = tooth * 2 * pi / 12 - pi / 2
        # Flat tooth crowns and short sloped flanks leave distinct root gaps.
        for degrees, radius in ((-15, 39), (-10, 39), (-7, 49),
                                (7, 49), (10, 39), (15, 39)):
            a = angle + degrees * pi / 180
            outline.append((center + radius * SCALE * cos(a),
                            center + radius * SCALE * sin(a)))
    draw.polygon(outline, fill=255)
    hole = 13 * SCALE
    draw.ellipse((center - hole, center - hole,
                  center + hole, center + hole), fill=0)
    antialiased = mask.resize((SIZE, SIZE), Image.Resampling.LANCZOS)
    return antialiased.point([0 if a < 5 else 255 if a > 250 else a
                              for a in range(256)])


def main() -> None:
    mask = render()
    data = mask.tobytes()
    lines = [
        "/* SPDX-License-Identifier: AGPL-3.0-or-later",
        " * Generated by firmware/tools/build_settings_icon_asset.py.",
        " * Antialiased, theme-tintable twelve-tooth Settings gear. */",
        "#pragma once", "",
        f"static const uint8_t ws_settings_gear_map[{len(data)}] = {{",
    ]
    for start in range(0, len(data), 20):
        lines.append("    " + ",".join(map(str, data[start:start + 20])) + ",")
    lines += [
        "};", "",
        "static const lv_img_dsc_t ws_settings_gear = {",
        "    .header.cf = LV_IMG_CF_ALPHA_8BIT,",
        "    .header.always_zero = 0,",
        "    .header.reserved = 0,",
        f"    .header.w = {SIZE},",
        f"    .header.h = {SIZE},",
        "    .data_size = sizeof(ws_settings_gear_map),",
        "    .data = ws_settings_gear_map,",
        "};", "",
    ]
    OUT.write_text("\n".join(lines), encoding="utf-8")
    preview = Image.new("RGB", (180, 180), "#000000")
    accent = Image.new("RGB", (SIZE, SIZE), "#4DE3C1")
    preview.paste(accent, (30, 30), mask)
    PREVIEW.parent.mkdir(parents=True, exist_ok=True)
    preview.save(PREVIEW)
    print(f"Generated {OUT} ({len(data)} A8 bytes)")
    print(f"Preview: {PREVIEW}")


if __name__ == "__main__":
    main()
