#!/usr/bin/env python3
"""Optional build-time generator of rendered GUI label sprites, not needed by Arduino.
Requires Pillow and two locally supplied font paths. No font files are bundled.
Example: python tools/build_gui_assets.py --regular PATH --semibold PATH
"""
from __future__ import annotations
import argparse
from pathlib import Path
from PIL import Image, ImageDraw, ImageFont

ROOT = Path(__file__).resolve().parents[1]
# Complete, fixed UI labels are rasterized once. Dynamic values use digit sprites.
LABELS = [('BRAND', 'PICO FIDO', 19, True), ('ENTER_PIN', 'Enter PIN', 30, True), ('SCOPE_LOGIN', 'Sign in', 18, True), ('SCOPE_REGISTER', 'Create credential', 18, True), ('SCOPE_BOTH', 'Register / sign in', 18, True), ('SCOPE_CREDENTIALS', 'Manage credentials', 18, True), ('SCOPE_SETTINGS', 'Device settings', 18, True), ('SCOPE_DATA', 'Credential data', 18, True), ('SCOPE_READ', 'Read credentials', 18, True), ('SCOPE_MULTIPLE', 'Multiple permissions', 18, True), ('SCOPE_NONE', 'Verify identity', 18, True), ('DIGITS', 'digits', 17, False), ('TRIES', 'tries', 18, True), ('SECONDS', 's', 18, True), ('CANCEL', 'Cancel', 24, True), ('APPROVE', 'Approve', 26, True), ('VERIFY', 'Verify', 20, True), ('YOUR_APPROVAL', 'Confirm request', 28, True), ('ONLY_APPROVE', 'Only approve', 22, False), ('YOU_STARTED', 'your own request.', 22, False), ('READY', 'Ready', 38, True), ('START_HOST', 'Start sign-in on', 22, False), ('YOUR_COMPUTER', 'your computer.', 22, False), ('USB_FIDO', 'USB connected', 19, True), ('TOUCH_MISSING', 'Touch unavailable', 21, True), ('BOOT', 'Press BOOT', 25, True), ('CANCEL_HOST', 'Cancel on computer', 21, True), ('PROCESSING', 'Processing', 33, True), ('PLEASE_WAIT', 'Please wait...', 23, False), ('KEEP_CONNECTED', 'Keep USB connected.', 21, False), ('CONFIRMED', 'Accepted', 38, True), ('CHECK_RESULT', 'Continue on your', 22, False), ('COMPUTER', 'computer.', 22, False), ('CANCELLED', 'Cancelled', 36, True), ('NOT_APPROVED', 'Request stopped.', 22, False), ('START_AGAIN', 'Start again to retry.', 22, False), ('TIMED_OUT', 'Time expired', 33, True), ('NO_CONFIRM', 'Request timed out.', 22, False), ('PIN_BAD', 'Incorrect PIN', 32, True), ('RETRY_HOST', 'Try again from', 22, False), ('PIN_LOCKED', 'PIN unavailable', 29, True), ('CHECK_RETRIES', 'Check PIN retries', 22, False), ('ON_COMPUTER', 'on your computer.', 22, False), ('INPUT_ERROR', 'Input unavailable', 28, True), ('CHECK_TOUCH', 'Check the display', 22, False), ('AND_TOUCH', 'and touch input.', 22, False), ('CONNECT', 'Connect USB', 34, True), ('USE_CABLE', 'Connect to your', 22, False), ('STANDBY', 'Standby', 38, True), ('WAITING_FOR', 'Waiting for a', 22, False), ('SIGN_IN_REQUEST', 'sign-in request.', 22, False), ('KEEP_AWAKE', 'Tap to keep awake', 20, False)]

def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument('--regular', type=Path, required=True)
    ap.add_argument('--semibold', type=Path, required=True)
    ap.add_argument('--output', type=Path, default=ROOT/'templates/port/ws_gui_assets.h')
    args=ap.parse_args()
    for path in (args.regular,args.semibold):
        if not path.is_file(): ap.error(f'Missing local font: {path}')
    fonts={}
    def font(size,bold):
        key=(size,bold)
        if key not in fonts: fonts[key]=ImageFont.truetype(str(args.semibold if bold else args.regular),size*3)
        return fonts[key]
    labels=LABELS+[(f'NUM_{n}',str(n),34,True) for n in range(10)]+[(f'SMALL_{n}',str(n),18,True) for n in range(10)]
    data=[];offsets=[];sprites=[]
    for name,text,size,bold in labels:
        f=font(size,bold)
        # Fixed em-box for all digits of one size, so numbers never jump vertically.
        baseline=size*3
        width=(round(f.getlength(text))+2)//3+2
        height=size+5
        im=Image.new('L',(width*3,height*3),0)
        ImageDraw.Draw(im).text((0,baseline),text,font=f,fill=255,anchor='ls')
        im=im.resize((width,height),Image.Resampling.LANCZOS)
        vals=list(im.get_flattened_data()) if hasattr(im,'get_flattened_data') else list(im.getdata())
        row0=len(offsets)
        for y in range(height):
            offsets.append(len(data))
            row=[(vals[y*width+x]*15+127)//255 for x in range(width)]
            x=0
            while x<width:
                end=x+1
                while end<width and end-x<16 and row[end]==row[x]:end+=1
                data.append(((end-x-1)<<4)|row[x]);x=end
        sprites.append((name,width,height,row0))
    offsets.append(len(data))
    out=['/* SPDX-License-Identifier: AGPL-3.0-or-later */',
         '/* Rendered UI label images (4-bit alpha, per-row RLE). Not a font file.',
         ' * Generated by tools/build_gui_assets.py. No runtime font dependency. */',
         '#pragma once','#include <stdint.h>',
         'typedef struct { uint16_t width,height,first_row; } ws_gui_sprite_t;',
         'enum {']
    out += [f'    WS_GFX_{name},' for name,*_ in sprites]
    out += ['    WS_GFX_COUNT','};','static const ws_gui_sprite_t ws_gui_sprites[] = {']
    out += [f'    {{{w},{h},{row}}}, /* {name} */' for name,w,h,row in sprites]
    out += ['};','static const uint32_t ws_gui_row_offsets[] = {']
    for start in range(0,len(offsets),12):out.append('    '+','.join(map(str,offsets[start:start+12]))+',')
    out += ['};','static const uint8_t ws_gui_alpha_rle[] = {']
    for start in range(0,len(data),24):out.append('    '+','.join(f'0x{b:02x}' for b in data[start:start+24])+',')
    out+=['};','']
    args.output.parent.mkdir(parents=True,exist_ok=True)
    args.output.write_text('\n'.join(out),encoding='utf-8')
    print(f'{len(sprites)} rendered labels; {len(data)} RLE bytes; {len(offsets)*4} row-index bytes.')
if __name__=='__main__':main()
